export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',
    ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',
    ADD_USER_ORDER_REQUEST: ' ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS: ' ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILURE: ' ADD_USER_ORDER_FAILURE',
    
    GET_USER_ORDER_REQUEST : 'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS : 'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_FAILURE : 'GET_USER_ORDER_FAILURE',

    GET_ORDER_DETAILS_REQUEST : 'GET_ORDER_DETAILS_REQUEST',
    GET_ORDER_DETAILS_SUCCESS : 'GET_ORDER_DETAILS_SUCCESS',
    GET_ORDER_DETAILS_FAILURE : 'GET_ORDER_DETAILS_FAILURE',
}


export const CatConstants = {
    GET_ALL_CAT_REQUEST: 'GET_ALL_CAT_REQUEST',
    GET_ALL_CAT_SUCCESS: 'GET_ALL_CAT_SUCCESS',
    GET_ALL_CAT_FAILURE: 'GET_ALL_CAT_FAILURE',
    ADD_NEW_CAT_REQUEST: 'ADD_NEW_CAT_REQUEST',
    ADD_NEW_CAT_SUCCESS: 'ADD_NEW_CAT_SUCCESS',
    ADD_NEW_CAT_FAILURE: 'ADD_NEW_CAT_FAILURE',
}

export const ProductConstants = {
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
    GET_PAGE_REQUEST: 'GET_PAGE_REQUEST',
    GET_PAGE_SUCCESS: 'GET_PAGE_SUCCESS',
    GET_PAGE_FAILURE: 'GET_PAGE_FAILURE',

    GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST',
    GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
    GET_PRODUCT_DETAILS_FAILURE: 'GET_PRODUCT_DETAILS_FAILURE',
}


export const CartConstants = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    RESET_CART: 'RESET_CART'
}