export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
}

export const CatConstants = {
    GET_ALL_CAT_REQUEST: 'GET_ALL_CAT_REQUEST',
    GET_ALL_CAT_SUCCESS: 'GET_ALL_CAT_SUCCESS',
    GET_ALL_CAT_FAILURE: 'GET_ALL_CAT_FAILURE',
    ADD_NEW_CAT_REQUEST: 'ADD_NEW_CAT_REQUEST',
    ADD_NEW_CAT_SUCCESS: 'ADD_NEW_CAT_SUCCESS',
    ADD_NEW_CAT_FAILURE: 'ADD_NEW_CAT_FAILURE',
    UPDATE_CAT_REQUEST:  'UPDATE_CAT_REQUEST',
    UPDATE_CAT_SUCCESS:  'UPDATE_CAT_SUCCESS',
    UPDATE_CAT_FAILURE:  'UPDATE_CAT_FAILURE', 
    DELETE_CAT_REQUEST: 'DELETE_CAT_REQUEST',
    DELETE_CAT_SUCCESS: 'DELETE_CAT_SUCCESS',
    DELETE_CAT_FAILURE: 'DELETE_CAT_FAILURE',
}

export const InitalConstants = {
    GET_ALL_DATA_REQUEST: 'GET_ALL_DATA_REQUEST',
    GET_ALL_DATA_SUCCESS: 'GET_ALL_DATA_SUCCESS',
    GET_ALL_DATA_FAILURE: 'GET_ALL_DATA_FAILURE',
    
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',  
}

export const pageConstants = {
    ADD_NEW_PAGE_REQUEST: 'ADD_NEW_PAGE_REQUEST',
    ADD_NEW_PAGE_SUCCESS: 'ADD_NEW_PAGE_SUCCESS',
    ADD_NEW_PAGE_FAILURE: 'ADD_NEW_PAGE_FAILURE',
}

export const orderConstants = {
    GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

    UPDATE_ORDER_REQUEST: 'UPDATE_ORDER_REQUEST',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_FAILURE: 'UPDATE_ORDER_FAILURE',
}